pkg: pine64: linux-megi: add build flags to support mimic
To be able to use [mimic][0] with [default `kfunc` checksum hack][1]
with [aur/mimic-bpf-git][2], it requires some kernel build flags that
exist in upstream Arch Linux linux package but does not exist in
danctnix linux-megi package. This commit is trying to add those kernel
build flags and related PKGBUILD changes to make mimic work with
danctnix linux-megi package on pinephone.

[mimic doc here][1] wrote it needs `CONFIG_BPF_JIT=y` and
`CONFIG_DEBUG_INFO_BTF=y` build flags. Our pkg already has
`CONFIG_BPF_JIT=y`. We need `CONFIG_DEBUG_INFO_BTF=y`. [Kernel
kconfig][3] wrote DEBUG_INFO_BTF needs `PAHOLE_VERSION >= 116`, so I
change `CONFIG_PAHOLE_VERSION=0` to `CONFIG_PAHOLE_VERSION=130` in
"config" file and add pahole depends to PKGBUILD; without these changes,
kernel will not be built with `CONFIG_DEBUG_INFO_BTF=y` because its
dependencies are not satisfied, see this [stackoverflow answer][4].

`CONFIG_DEBUG_INFO_BTF_MODULES=y` is also needed, else there will be
errors like:

    mimic[100]:  Warn libbpf: extern (func ksym) 'mimic_change_csum_offset': not found in kernel or module BTFs
    mimic[100]:  Warn libbpf: failed to load object 'mimic_bpf'
    mimic[100]:  Warn libbpf: failed to load BPF skeleton 'mimic_bpf': -22
    mimic[100]: Error failed to load BPF program: Invalid argument
    systemd[1]: mimic@wlan0.service: Main process exited, code=exited, status=22/n/a
    systemd[1]: mimic@wlan0.service: Failed with result 'exit-code'.
    systemd[1]: Failed to start Start Mimic on wlan0.

With `CONFIG_DEBUG_INFO_BTF_MODULES=y`, we also need these added to
PKGBUILD, these are take from official Arch Linux's linux PKGBUILD:

    # required when DEBUG_INFO_BTF_MODULES is enabled
    install -Dt "$builddir/tools/bpf/resolve_btfids" tools/bpf/resolve_btfids/resolve_btfids

Without above one line shell script added to PKGBUILD,
[aur/mimic-bpf-git][2] will have build errors like:

    [xyz@xyzpp build]$ cat /var/lib/dkms/mimic/0.7.0.r5.572a2ae/build/make.log
    DKMS (dkms-3.2.1) make.log for mimic/0.7.0.r5.572a2ae for kernel 6.15.6-2-megi-danctnix (aarch64)
    Tue Jul 29 07:30:00 PM CST 2025

    Building module(s)
    # command: make -j4 KERNELRELEASE=6.15.6-2-megi-danctnix KERNEL_UNAME=6.15.6-2-megi-danctnix
    cp -rL /lib/modules/6.15.6-2-megi-danctnix/build overlay
    ERROR: `resolve_btfids` not found; please compile it from Linux kernel source and re-run make with RESOLVE_BTFIDS=<path>
    make: *** [Makefile:72: build] Error 1

    # exit code: 2
    # elapsed time: 00:00:06

`CONFIG_NET_SCH_INGRESS=m` is also needed, else there will be errors like:

    mimic[100]:  Warn libbpf: Kernel error message: Specified qdisc kind is unknown
    mimic[100]: Error failed to create TC egress hook: No such file or directory
    mimic[100]:  Warn libbpf: Kernel error message: Parent Qdisc doesn't exists

First I only added and edited "config" file with
`CONFIG_PAHOLE_VERSION=130`, `CONFIG_NET_SCH_INGRESS=m`, and
`CONFIG_DEBUG_INFO_BTF=y`. Then I ran `makepkg -s`. I think `make
prepare` in the PKGBUILD will prompt me to choose more build flags,
these are my choices:

    Extensible Scheduling Class (SCHED_CLASS_EXT) [N/y/?] (NEW) n
    Generate BTF type information for kernel modules (DEBUG_INFO_BTF_MODULES) [Y/n/?] (NEW) y
      Allow loading modules with non-matching BTF type info (MODULE_ALLOW_BTF_MISMATCH) [N/y/?] (NEW) n
      Support BTF function arguments for probe events (PROBE_EVENTS_BTF_ARGS) [Y/n/?] (NEW) n

As you can see, I only choose y for DEBUG_INFO_BTF_MODULES because I
need this for mimic to work, all others are not needed. At last, I copy
from src/linux/.config to "config" file, this is the final "config" file
content in this commit, note some are auto generated by `make prepare`.

I compiled with this commit locally on pinephone and the test shows this
commit indeed can make mimic run on pinephone. But I'm a noob and I
don't understand mimic or kernel code and I only make it work through
trial and error, so take these with a grain of salt. There are things I
don't understand. For example, [mimic doc here][6] wrote there are
situations checksum hack are not necessary but I don't know if pinephone
fits the situation or not. I tested networking, phone call, SMS message
etc. on pinephone and everything seems working, I did not test other
devices.

[0]: https://github.com/hack3ric/mimic
[1]: https://github.com/hack3ric/mimic/blob/572a2ae5aeaa156afc2d6064a763e842962735bf/docs/checksum-hacks.md?plain=1#L15
[2]: https://aur.archlinux.org/packages/mimic-bpf-git
[3]: https://codeberg.org/megi/linux/src/commit/c0c8fa8103dfc8577711f70cc4434773c33c2970/lib/Kconfig.debug#L382
[4]: https://stackoverflow.com/a/69552666
[5]: https://github.com/hack3ric/mimic/blob/572a2ae5aeaa156afc2d6064a763e842962735bf/docs/checksum-hacks.md?plain=1#L41-L42
[6]: https://github.com/hack3ric/mimic/blob/572a2ae5aeaa156afc2d6064a763e842962735bf/docs/checksum-hacks.md?plain=1#L21

Signed-off-by: Xiao Pan <xyz@flylightning.xyz>